name: Bridge e2e test

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types: [completed]
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run id from which artifacts are taken"
        required: true

jobs:
    e2e-bridge-test:
        runs-on: self-hosted
        steps:
            - name: Retrieve run id
              id: retrieve-run-id
              run: |
                  if [[ -n "${{ github.event_name == 'workflow_dispatch' }}" ]]; then
                    echo "run_id=${{ github.event.inputs.run_id }}" >> $GITHUB_OUTPUT
                  else
                    echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
                  fi
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ needs.set-tags.outputs.git_ref }}
            - name: Check g++
              id: setup_g_plusplus
              run: |
                g++ --version
            - name: Check protoc
              id: check_proto_c
              run: |
                protoc --version
            - name: Check jq
              id: check_jq
              run: |
                jq --version
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '^1.22.0'
            - name: Check go
              id: check_go
              run: |
                go version
            - name: Run Mage
              uses: magefile/mage-action@v3
              with:
                install-only: true
            - name: Check mage
              id: check_mage
              run: |
                mage --version
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
            - name: Check forge
              id: check_forge
              run: |
                forge --version
            - name: Pnpm
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
            - name: Install yarn
              run: |-
                curl -fsSL --create-dirs -o $HOME/bin/yarn \
                https://github.com/yarnpkg/yarn/releases/download/v1.22.22/yarn-1.22.22.js
                chmod +x $HOME/bin/yarn
                echo "$HOME/bin" >> $GITHUB_PATH
            - name: Check yarn
              id: check_yarn
              run: |
                yarn --version
            - name: Check date
              id: check_date
              run: |
                date --version
            - name: Download build artifact from triggered workflow
              uses: dawidd6/action-download-artifact@v2
              with:
                run_id: ${{ steps.retrieve-run-id.outputs.run_id }}
                name: binaries
                path: binaries
                search_artifacts: true
            - name: Upload binaires
              uses: actions/upload-artifact@v4
              with:
                  name: binaries
                  path: binaries
            - name: Run Zombienet Test zombie_tanssi_relay_eth_bridge
              uses: ./.github/workflow-templates/zombienet-tests
              with:
                test_name: zombie_tanssi_relay_eth_bridge